-- This migration has been superseded by 20260622000001_relay/migration.sql
-- It is kept here only as a placeholder so the migrations directory structure is intact.
-- DO NOT apply this migration to a new database.
