ALTER TABLE "Profile" ADD COLUMN IF NOT EXISTS "accentColor" TEXT;
ALTER TABLE "Profile" ADD COLUMN IF NOT EXISTS "bgColor" TEXT;
ALTER TABLE "Profile" ADD COLUMN IF NOT EXISTS "gradientFrom" TEXT;
ALTER TABLE "Profile" ADD COLUMN IF NOT EXISTS "gradientTo" TEXT;
ALTER TABLE "Profile" ADD COLUMN IF NOT EXISTS "bannerUrl" TEXT;
